# Copyright © 2025 Jalapeno Labs

services:
  frontend:
    build: Dockerfile.dev
    restart: unless-stopped
    container_name: steamworkshop_watcher_frontend
    volumes:
      - package.json:/app/package.json
      - yarn.lock:/app/yarn.lock
      - tsconfig.json:/app/tsconfig.json
      - src/:/app/src/
      - ./.cache:/app/.cache
    environment:
      NODE_ENV: development
      WEBHOOK_URL: ${WEBHOOK_URL}
      WORKSHOP_PAGES: ${WORKSHOP_PAGES}
      BLACKLIST_USERS: ${BLACKLIST_USERS}
