# Copyright © 2025 Jalapeno Labs

name: Build & Validate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Setup:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      # Install dependencies & make assets
      - name: Install dependencies
        id: install
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install

      - name: Ensure linted
        id: lint
        run: yarn lint
        continue-on-error: true

      # Typescript checking
      - name: Check types
        id: typescript
        run: yarn typecheck
        continue-on-error: true

      - name: Check if any of the previous steps failed
        run: |
          # Initialize a failure flag
          FAILURE=false

          # Check the lint step
          if [ "${{ steps.lint.outcome }}" != "success" ]; then
            echo "Lint: FAILED"
            FAILURE=true
          else
            echo "Lint: SUCCESS"
          fi

          # Check the TypeScript step
          if [ "${{ steps.typescript.outcome }}" != "success" ]; then
            echo "TypeScript: FAILED"
            FAILURE=true
          else
            echo "TypeScript: SUCCESS"
          fi

          # Exit with failure if any step failed
          if [ "$FAILURE" = true ]; then
            echo "One or more steps failed."
            exit 1
          fi
